const { invoke, convertFileSrc } = window.__TAURI__.core;
let settings=null, runtime=null, saveTimer=null, captureBusy=false, coordCaptureBusy=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const hotkeyButtons={clicker1:'#c1-hotkey',clicker2:'#c2-hotkey',bolt_push:'#bp-hotkey',bolts:'#bolts-hotkey'};

const I18N={
 ru:{nav_home:'Главная',nav_clicker:'Кликер',nav_macros:'Макросы',nav_coords:'Координаты',nav_lobby:'Лобби',nav_settings:'Настройки',stop_all:'ОСТАНОВИТЬ ВСЁ · F12',hero_title:'Сначала работа макросов. Без мусора в интерфейсе.',hero_text:'Надёжные нажатия, захват координат через F6 и простой интерфейс.',open_macros:'ОТКРЫТЬ МАКРОСЫ',open_coords:'КООРДИНАТЫ',clicker_title:'Автокликер',toggle:'ВКЛ / ВЫКЛ',mouse_button:'Кнопка мыши',macros_title:'Макросы',macros_sub:'Оба макроса можно держать включёнными одновременно.',target_coord:'Координата цели',arm_f6:'F6 КООРД.',test_macro:'ТЕСТ МАКРОСА',reliable_timing:'Надёжные нажатия',reliable_text:'Каждая V реально нажимается и отпускается. Никаких 1 мс нажатий.',coords_title:'Координаты',arm_f6_capture:'ЗАХВАТИТЬ ЧЕРЕЗ F6',capture_now:'СОХРАНИТЬ СЕЙЧАС',f6_how_title:'Как работает F6',f6_how_text:'Нажми «Захватить через F6», переключись в игру, наведи курсор куда надо и нажми F6. Новая точка сразу выберется для Bolt Push.',lobby_title:'Macro Lobby',owner:'Создатель',member:'Участник',name:'Имя',create_lobby:'СОЗДАТЬ ЛОББИ',code:'Код',join_code:'Код подключения',join:'ПОДКЛЮЧИТЬСЯ',leave:'ВЫЙТИ',settings_title:'Настройки',language:'Язык',lang_hint:'Меняется сразу и сохраняется.',background:'Фон',choose_media:'ВЫБРАТЬ ФОТО / ВИДЕО',clear:'ОЧИСТИТЬ',appearance:'Внешний вид',panel_opacity:'Прозрачность панелей',intro:'Заставка при запуске',updates:'Обновления',current_version:'Текущая версия',update_hint:'Автообновление будет брать новые версии из GitHub Releases. Пока новой версии нет — остаётся 1.0.'},
 en:{nav_home:'Home',nav_clicker:'Clicker',nav_macros:'Macros',nav_coords:'Coordinates',nav_lobby:'Lobby',nav_settings:'Settings',stop_all:'STOP ALL · F12',hero_title:'Macros first. No UI clutter.',hero_text:'Reliable key timing, direct F6 coordinate capture and a simpler control layout.',open_macros:'OPEN MACROS',open_coords:'COORDINATES',clicker_title:'Auto Clicker',toggle:'TOGGLE',mouse_button:'Mouse button',macros_title:'Macros',macros_sub:'Both macros can stay armed at the same time.',target_coord:'Target coordinate',arm_f6:'ARM F6',test_macro:'TEST MACRO',reliable_timing:'Reliable timing',reliable_text:'Each V has a real down/up cycle. No 1 ms fake taps.',coords_title:'Coordinates',arm_f6_capture:'ARM F6 CAPTURE',capture_now:'CAPTURE NOW',f6_how_title:'How F6 works',f6_how_text:'Press ARM F6, switch to the game, move the cursor to the target, then press F6. The new point is selected for Bolt Push automatically.',lobby_title:'Macro Lobby',owner:'Owner',member:'Member',name:'Name',create_lobby:'CREATE LOBBY',code:'Code',join_code:'Join code',join:'JOIN',leave:'LEAVE',settings_title:'Settings',language:'Language',lang_hint:'Changes immediately and is saved.',background:'Background',choose_media:'CHOOSE PHOTO / VIDEO',clear:'CLEAR',appearance:'Appearance',panel_opacity:'Panel opacity',intro:'Startup intro',updates:'Updates',current_version:'Current version',update_hint:'Auto-update will use GitHub Releases. Until a newer public version exists, this stays 1.0.'}
};
const pageNames={home:{ru:'Главная',en:'Home'},clicker:{ru:'Автокликер',en:'Auto Clicker'},macros:{ru:'Макросы',en:'Macros'},coordinates:{ru:'Координаты',en:'Coordinates'},lobby:{ru:'Лобби',en:'Lobby'},settings:{ru:'Настройки',en:'Settings'}};

function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),1900)}
function lang(){return settings?.appearance?.language==='en'?'en':'ru'}
function applyLanguage(){const l=lang(),dict=I18N[l];document.documentElement.lang=l;$$('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(dict[k])el.textContent=dict[k]});$$('.lang button').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));const active=$('.nav.active')?.dataset.page||'home';$('#page-title').textContent=pageNames[active]?.[l]||'RiuClicker'}
function showPage(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${page}`));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#page-title').textContent=pageNames[page]?.[lang()]||'RiuClicker'}
$$('.nav,.jump').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));

function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(saveSettings,100)}
async function saveSettings(){if(!settings)return;try{await invoke('save_settings',{settings})}catch(e){toast(`Save: ${e}`)}}
function getHotkey(t){return settings[t]?.hotkey||''} function setHotkey(t,k){if(settings[t])settings[t].hotkey=k}
async function captureHotkey(target){if(captureBusy)return;captureBusy=true;const b=$(hotkeyButtons[target]);const old=b.textContent;b.classList.add('capturing');b.textContent=lang()==='ru'?'НАЖМИ КЛАВИШУ…':'PRESS KEY…';try{const key=await invoke('capture_hotkey');if(key){setHotkey(target,key);b.textContent=`HOTKEY · ${key}`;await saveSettings();toast(`${target.toUpperCase()} → ${key}`)}else b.textContent=old}catch(e){b.textContent=old;toast(String(e))}finally{b.classList.remove('capturing');captureBusy=false;renderDashboard()}}
Object.entries(hotkeyButtons).forEach(([k,s])=>$(s).addEventListener('click',()=>captureHotkey(k)));

function bind(id,get,set,kind='value',immediate=false){const el=$(id),ev=(el.type==='checkbox'||el.tagName==='SELECT')?'change':'input';el.addEventListener(ev,()=>{const v=kind==='checked'?el.checked:kind==='number'?Number(el.value):el.value;set(v);immediate?saveSettings():scheduleSave();renderDashboard()});return()=>{const v=get();if(kind==='checked')el.checked=!!v;else el.value=v}}
const refresh=[];
refresh.push(bind('#c1-cps',()=>settings.clicker1.cps,v=>settings.clicker1.cps=v,'number'));refresh.push(bind('#c2-cps',()=>settings.clicker2.cps,v=>settings.clicker2.cps=v,'number'));refresh.push(bind('#c1-mouse',()=>settings.clicker1.mouse_button,v=>settings.clicker1.mouse_button=v));refresh.push(bind('#c2-mouse',()=>settings.clicker2.mouse_button,v=>settings.clicker2.mouse_button=v));refresh.push(bind('#bp-enabled',()=>settings.bolt_push.enabled,v=>settings.bolt_push.enabled=v,'checked',true));refresh.push(bind('#bolts-enabled',()=>settings.bolts.enabled,v=>settings.bolts.enabled=v,'checked',true));refresh.push(bind('#squad-name',()=>settings.squad.display_name,v=>settings.squad.display_name=v));refresh.push(bind('#squad-port',()=>settings.squad.port,v=>settings.squad.port=v,'number'));refresh.push(bind('#lobby-e-action',()=>settings.squad.e_action,v=>settings.squad.e_action=v,'value',true));refresh.push(bind('#lobby-v-action',()=>settings.squad.v_action,v=>settings.squad.v_action=v,'value',true));refresh.push(bind('#intro-enabled',()=>settings.appearance.intro_enabled,v=>settings.appearance.intro_enabled=v,'checked'));

function renderHotkeys(){Object.entries(hotkeyButtons).forEach(([k,s])=>$(s).textContent=`HOTKEY · ${getHotkey(k)||'NONE'}`)}
function renderSpeeds(){$$('.speed').forEach(g=>g.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.speed===settings[g.dataset.action].speed)))}
$$('.speed button').forEach(b=>b.addEventListener('click',()=>{const a=b.closest('.speed').dataset.action;settings[a].speed=b.dataset.speed;renderSpeeds();saveSettings()}));

function selectedCoord(){return settings.coordinates.find(c=>c.id===settings.bolt_push.coordinate_id)||null}
function renderSelectedCoord(){const c=selectedCoord();$('#bp-coordinate-label').textContent=c?c.name:'NOT SET';$('#bp-coordinate-xy').textContent=c?`${c.x}, ${c.y}`:'—'}
function renderCoordinates(){const list=$('#coordinate-list');list.innerHTML='';if(!settings.coordinates.length){list.innerHTML=`<div class="empty">${lang()==='ru'?'Точек пока нет. Используй F6 или «Сохранить сейчас».':'No points yet. Use F6 capture or Capture Now.'}</div>`;renderSelectedCoord();return}settings.coordinates.forEach((c,i)=>{const card=document.createElement('div');card.className='coord-card'+(c.id===settings.bolt_push.coordinate_id?' selected':'');card.innerHTML=`<div class="row"><div><b>${esc(c.name)}</b><small>${c.x}, ${c.y}</small></div><span>${c.id.slice(-5)}</span></div><div class="coord-actions"><button class="use">${lang()==='ru'?'ИСПОЛЬЗОВАТЬ':'USE'}</button><button class="rename">${lang()==='ru'?'ИМЯ':'RENAME'}</button><button class="delete">${lang()==='ru'?'УДАЛИТЬ':'DELETE'}</button></div>`;card.querySelector('.use').onclick=e=>{e.stopPropagation();settings.bolt_push.coordinate_id=c.id;renderCoordinates();saveSettings()};card.onclick=()=>{settings.bolt_push.coordinate_id=c.id;renderCoordinates();saveSettings()};card.querySelector('.rename').onclick=e=>{e.stopPropagation();const n=prompt(lang()==='ru'?'Название точки':'Coordinate name',c.name);if(n?.trim()){c.name=n.trim().slice(0,32);renderCoordinates();saveSettings()}};card.querySelector('.delete').onclick=e=>{e.stopPropagation();settings.coordinates.splice(i,1);if(settings.bolt_push.coordinate_id===c.id)settings.bolt_push.coordinate_id=settings.coordinates[0]?.id||'';renderCoordinates();saveSettings()};list.appendChild(card)});renderSelectedCoord()}
function addCoordinate(x,y){const id=`P${Date.now().toString(36).toUpperCase()}`;const c={id,name:`Target ${settings.coordinates.length+1}`,x,y};settings.coordinates.push(c);settings.bolt_push.coordinate_id=id;renderCoordinates();saveSettings();toast(`${x}, ${y}`)}
async function armF6(button){if(coordCaptureBusy)return;coordCaptureBusy=true;const old=button.textContent;button.textContent=lang()==='ru'?'ЖДУ F6…':'WAITING F6…';button.disabled=true;toast(lang()==='ru'?'Переключись в игру, наведи курсор и нажми F6':'Switch to the game, aim cursor and press F6');try{const [x,y]=await invoke('capture_coordinate_f6');addCoordinate(x,y)}catch(e){toast(String(e))}finally{button.disabled=false;button.textContent=old;coordCaptureBusy=false}}
$('#capture-f6').addEventListener('click',e=>armF6(e.currentTarget));$('#bp-arm-f6').addEventListener('click',e=>armF6(e.currentTarget));$('#capture-now').addEventListener('click',async()=>{try{const [x,y]=await invoke('cursor_position');addCoordinate(x,y)}catch(e){toast(String(e))}});

$$('.run-action').forEach(b=>b.addEventListener('click',async()=>{try{await saveSettings();await invoke('run_action',{action:b.dataset.action});toast(lang()==='ru'?'Макрос запущен':'Macro started')}catch(e){toast(String(e))}}));$('#c1-toggle').addEventListener('click',async()=>{await saveSettings();await invoke('toggle_clicker',{slot:1})});$('#c2-toggle').addEventListener('click',async()=>{await saveSettings();await invoke('toggle_clicker',{slot:2})});$('#kill-all').addEventListener('click',()=>invoke('stop_all'));

$('#squad-host').addEventListener('click',async()=>{settings.squad.display_name=$('#squad-name').value.trim()||'Player';settings.squad.port=Number($('#squad-port').value)||42871;await saveSettings();try{const code=await invoke('host_lobby',{port:settings.squad.port});$('#squad-code').textContent=code;$('#squad-join-code').value=code;toast('Lobby created')}catch(e){toast(String(e))}});$('#squad-join').addEventListener('click',async()=>{try{await invoke('join_lobby',{code:$('#squad-join-code').value.trim(),name:$('#squad-name').value.trim()||'Player'});toast('Connected')}catch(e){toast(String(e))}});$('#squad-leave').addEventListener('click',async()=>{await invoke('leave_lobby');toast('Disconnected')});

$('#pick-bg').addEventListener('click',async()=>{const p=await invoke('pick_background');if(!p)return;settings.appearance.background_path=p;applyBackground(p);$('#bg-path').textContent=p;saveSettings()});$('#clear-bg').addEventListener('click',()=>{settings.appearance.background_path='';applyBackground('');$('#bg-path').textContent='No media selected';saveSettings()});function applyBackground(path){const box=$('#media-bg'),v=$('#bg-video');v.pause();v.removeAttribute('src');v.style.display='none';box.style.backgroundImage='none';if(!path)return;const src=convertFileSrc(path),ext=path.split('.').pop().toLowerCase();if(['mp4','m4v','mov','avi','wmv'].includes(ext)){v.src=src;v.style.display='block';v.play().catch(()=>{})}else box.style.backgroundImage=`url("${src}")`}
$('#panel-opacity').addEventListener('input',()=>{settings.appearance.panel_opacity=Number($('#panel-opacity').value)/100;$('#opacity-value').textContent=`${$('#panel-opacity').value}%`;applyOpacity();scheduleSave()});function applyOpacity(){const o=settings?.appearance?.panel_opacity??.88;document.documentElement.style.setProperty('--panel',`rgba(15,19,30,${o})`)}
$$('.lang button').forEach(b=>b.addEventListener('click',()=>{settings.appearance.language=b.dataset.lang;applyLanguage();renderCoordinates();saveSettings()}));

function renderDashboard(){if(!settings)return;$('#dash-c1-meta').textContent=`${settings.clicker1.hotkey||'NONE'} · ${settings.clicker1.cps} CPS`;$('#dash-c2-meta').textContent=`${settings.clicker2.hotkey||'NONE'} · ${settings.clicker2.cps} CPS`;const a=[];if(settings.bolt_push.enabled)a.push(`Bolt Push ${settings.bolt_push.hotkey}`);if(settings.bolts.enabled)a.push(`Bolts ${settings.bolts.hotkey}`);$('#dash-macros').textContent=a.length?'ARMED':'READY';$('#dash-macros-meta').textContent=a.join(' · ')||'Both available'}
function renderAll(){refresh.forEach(f=>f());renderHotkeys();renderSpeeds();renderCoordinates();renderDashboard();$('#panel-opacity').value=Math.round(settings.appearance.panel_opacity*100);$('#opacity-value').textContent=`${$('#panel-opacity').value}%`;$('#bg-path').textContent=settings.appearance.background_path||'No media selected';applyBackground(settings.appearance.background_path);applyOpacity();applyLanguage();if(!settings.appearance.intro_enabled)$('#intro').style.display='none'}
async function poll(){try{runtime=await invoke('runtime_snapshot');$('#runtime-message').textContent=runtime.last_message;$('#c1-state').textContent=runtime.clicker1_running?'ON':'OFF';$('#c2-state').textContent=runtime.clicker2_running?'ON':'OFF';$('#dash-c1').textContent=runtime.clicker1_running?'RUNNING':'OFF';$('#dash-c2').textContent=runtime.clicker2_running?'RUNNING':'OFF';$('#squad-role').textContent=runtime.lobby_role;$('#dash-lobby').textContent=runtime.lobby_role;$('#squad-members').textContent=`${runtime.lobby_members} MEMBER${runtime.lobby_members===1?'':'S'}`;if(runtime.lobby_code)$('#squad-code').textContent=runtime.lobby_code;$('#dash-lobby-meta').textContent=runtime.lobby_role==='OFFLINE'?'Owner hosted':`${runtime.lobby_members} connected`;const names=runtime.lobby_member_names||[];$('#squad-member-list').innerHTML=names.map(n=>`<span class="member-chip">${esc(n)}</span>`).join('')}catch{}}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
(async()=>{try{settings=await invoke('get_settings');if(!settings.appearance)settings.appearance={};settings.appearance.language=settings.appearance.language||'ru';renderAll();await poll();setInterval(poll,120)}catch(e){toast(`Startup: ${e}`)}})();
