[package]
name = "riu-clicker-pro"
version = "2.0.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2" }

[dependencies]
tauri = { version = "2" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
parking_lot = "0.12"
rfd = "0.15"
local-ip-address = "0.6"
windows-sys = { version = "0.59", features = [
  "Win32_Foundation",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging"
] }
